### PR TITLE
V4 - Improve performance/React hooks

### LINKED ISSUE #130: Optimize the components
Hello! Loving the app as it does a great job overall!

So I've been using this component for some time now and while it does the job well, it does cause some needless rerenders that can be easily fixed if you were opened to making some modifications to the apps. I enabled this library https://github.com/welldone-software/why-did-you-render during my development to kink out performance issues early on and this is the last thing on the list. 

Wanted to see if turning these components into PureComponents would intrigue you on the basis that SectionList  https://reactnative.dev/docs/sectionlist and  Flatlist https://reactnative.dev/docs/flatlist are PureComponents per docs so 
 More specifically using React.memo and turning these components into functional components to leverage hooks `useCallback` and `useMemo` and only updating when absolutely necessary. 

I've already proved out the concept with SectionGrid and am happy to make a PR request for it. I have business specific specs locally that I leveraged in order to do this refactor and here are breaking changes that would occur. I would of added tests but theres no underlying structure for it so punted on that. But would suggest react-testing-library and using `inlineSnapshots` to do assertions regarding what gets rendered in the list. 

https://github.com/IsaaX/react-native-super-grid/commit/f1c26b2958e041ac82033fd41c2df1588c8c9a54
 

Breaking changes:
React - 16.8 would be required for hooks 
References now get updated a bit relatively to what it was done previously 
`ref.current.sectionList.scrollToLocation` -> `ref.current.scrollToLocation` due to forwardRef

### PR DESCRIPTION
**Pull request by saleel**
- Improve SectionList performance by using hooks @IsaaX
- Improve FlatList performance by using hooks

Fixes #130

### CODE REVIEW

**Comment by saleel** [comment]
@IsaaX I have also modified the FlatList to use hooks/optimizations.
I guess it is good to be merged to master. Please have a look if you have some time.

**Comment by ianmartorell** [comment]
In v3, I used to get rid of the empty space at both sides of the grid by applying a negative `marginHorizontal` equal to the spacing between the items. However, in v4 the grid doesn't stretch to span the full width when doing that:

Without negative `horizontalMargin`:
Screen Shot 2020-05-24 at 11 47 25

With negative `horizontalMargin` in v3:
Screen Shot 2020-05-24 at 11 50 59

With negative `horizontalMargin` in v4:
Screen Shot 2020-05-24 at 11 47 57

Is there another way to get rid of that empty space at both sides of the grid?

**Comment by saleel** [comment]
@ianmartorell I checked it and negative margins are working fine in FlatGrid but not in SectionGrid.
This is because of the new View component introduced on top of SectionGrid from what I see.

@IsaaX Can you have a look at the above issue? Is the View wrapper absolutely required?  I tested without it, and the rendering and onLayout is working well for me.

**Comment by IsaaX** [comment]
@saleel After investigating, I cannot reproduce the issue in which the <View> was introduced in the first place. Possibly could have changed due to the latest iteration I submitted for pull request. Not sure exactly what changed but I'm good without it so I submitted a PR to reflect that https://github.com/saleel/react-native-super-grid/pull/137

**Comment by saleel** [comment]
@IsaaX Great. 👍 

@ianmartorell Can you test again with the new changes merged to v4 please?

**Comment by saleel** [comment]
I have tested the changes and works fine. 
Published version 4.0.0 to npm.

**Pull request merged**
