### PR TITLE
Add maxItemsPerRow to limit number of items in a row

### PR DESCRIPTION
**Pull request by levic92**

### CODE REVIEW

**Comment by saleel** [comment]
Hi @levic92 

Sorry for the delay. Can I ask what is the use case behind this change? 

This library decide the number of items to render in a row based on the available screen width and given itemDimension. 
If we set a maxItemsPerRow and the available width could have rendered a lot more, then the value specified for `itemDimension` become meaningless. The idea behind this library is to render items in a responsive manner, so you can have same/similar itemWidth when you are on a phone or a tablet or a laptop (number of items rendered would increase as screen size increase)
If you want to target a specific device size (only mobile phones for example) you can tune itemDimension value to get the desired number of items in a row.

**Comment by levic92** [comment]
I disagree with your statement that `itemDimension` becomes meaningless. In the documentations it says `you pass itemDimension and each item will be rendered with a dimension size equal to or more than (to fill the screen) the given dimension.` Based on that, `itemDimension` is the smallest the item will possibly be, but will be bigger if it can't fit multiple in a single row. So if you set itemDimension to 150 it could possibly be rendered at double the size depending on the spacing you set.

There are plenty of use cases for this but it really comes down to the way content is presented based on screen size. In my use case I have set an item size around 150 and generally on a mobile device in portrait mode this will render 2 items in a row. That is great and what I am wanting, but on a desktop if I use the default behaviour of the library I will get 6 items in a row. I would prefer my UI on the desktop only show 3 items but a lot larger. The reason for this is people generally are sitting further away from a desktop monitor than their phone screen. This PR accomplishes that. 

The initial intent behind the library has not changed and there is no change if you do not pass `maxItemsPerRow`, but more configurability is added to enable more control of the UI you want to create.

**Comment by levic92** [comment]
I do believe this is behaviour that other may want, but it is your library and I understand if you decide to not merge this. Thanks for the great library

**Review by saleel — APPROVED** [review]

**Comment by saleel** [comment]
Merged and released v4.3.0

**Comment by levic92** [comment]
Thanks for doing this so quickly!

**Pull request merged**
