### PR TITLE
Add support for full width items

### PR DESCRIPTION
**Pull request by DevChanQ**
Thanks for this awesome library! I have been using it for quite a few of my projects already. Recently I encountered an use case which needed support for full width items but the library didn't support this feature #203. That's why I decided to implement it myself! 

To make an item full width, all you have to do is to include `fullWidth: true` in the data object for that item.

Let me know if this looks good to you :)

### CODE REVIEW

**Comment by saleel** [comment]
Hey @DevChanQ 

This is amazing. Thank you :-)

Would you be able to add this for SectionGrid as well so its consistent?

Also please update the README doc with the new prop.

**Comment by DevChanQ** [comment]
No problem!

**Comment by DevChanQ** [comment]
Pushed commits to SectionGrid & SimpleGrid, also made some changes to the array chunking function as well. Have a look and see if everything's ok :)

**Comment by saleel** [comment]
Thank you. Merged and released version 5.1.0.

I renamed `fullWidth` to `_fullWidth` to avoid conflict in case people have fullWidth in data for something else. https://github.com/saleel/react-native-super-grid/commit/34c7d8e2c3d372224d03756dd47da89cc1ce0de6

There was also a tiny bug [here](https://github.com/saleel/react-native-super-grid/commit/eec98c28194a476bab1a5fa6d075643cb0da8af3#diff-7976027e5e7d8d8f13acd871bd9feef3d81d67f325b1f891a02da6b09c3d9ee8R84).

**Pull request merged**
