### PR TITLE
Improve Performance

### PR DESCRIPTION
**Pull request by Secretmapper**
- Switch to FlatList
- Use StyleSheet.create
- Minimize render calculations
- Cache row chunking

Took a stab into using the much faster 0.43 FlatList. As well, I added a bunch of optimizations like StyleSheet.create and pushing row chunking to state. I did not profile, but in our app with a very long list and many update operations (search and filter), the improvement is very visible.

### CODE REVIEW

**Comment by saleel** [comment]
This is great. I will test it out and merge shortly.

**Comment by saleel** [comment]
Hi @Secretmapper 

I tested this PR and I really appreciate the switch to FlatList. 

I tested with the demo code in the main Readme and the blocks were displayed with incorrect widths. Though changing

```
item: {
    alignSelf: 'center'
}
```
to
```
item: {
    alignSelf: 'stretch'
}
```

did almost fix it.

But I notice that you have hard coded paddingBottom and marginBottom for "row" as 10. We were using the passed `spacing` prop earlier.

Please make these changes and resubmit PR and I will approve. Also make sure all current props are working as intended.

**Comment by Secretmapper** [comment]
Oops, that was a carryover from the project. Just updated it and added 'stretch' as well.

**Comment by saleel** [comment]
simulator screen shot - iphone 6 - 2017-10-29 at 22 01 11
simulator screen shot - iphone 6 - 2017-10-29 at 22 01 08

I tested the new code with the example app. See the above two screenshots.

In the first one, spacing is not correct (side spacing is not same as up/down spacing). I see you have removed the hardcoded "10", but we used to set the padding dynamically in the code before.
In the second image the two blocks are taking full width instead of passed prop.

There could be other inconsistencies I have not tested too. Need to be sure this is fully backward compatible. I would say we do the FlatList + Stylesheet.Create first without changing other stuffs. I don't have much time to do it myself right now. I would appreciate if you could fix these and make sure everything works as before (by using the example code)

**Comment by saleel** [comment]
Hi @Secretmapper 

Are you working on this? If not, I will have a look.

Btw, you can ignore "Also the bottom portion is cropped (below the scroll view)" in my last message.   That was only because of styling issues in my testing code.

**Comment by Secretmapper** [comment]
Hello @saleel 

I do plan on looking this over but just have a couple of things on my plate right now. Feel free to work on it if you wish!

**Comment by saleel** [comment]
Ok. Its better you do it when you have time. I am busy too at the moment.

**Comment by Angelk90** [comment]
@Secretmapper , @saleel : Could you add my request in the new version?
Link: https://github.com/saleel/react-native-super-grid/issues/21

**Pull request closed without merging**
