### PR TITLE
Use jsx extension for files with jsx content

### PR DESCRIPTION
**Pull request by sequoiaKozak**
I'm getting compilation errors with my project because it doesn't recognize jsx content in .js files. Changing the extension to .jsx fixes it, and as far as I know shouldn't cause any new issues.

### CODE REVIEW

**Comment by saleel** [comment]
Can you share the error message here?

Are you using this library via npm? Ideally, the bundler is supposed to take care of file resolution and both js and jsx should work. Do you have some linter in your project that enforce this file extensions rule? I don't think all react native libraries have jsx as extension. 

Renaming is probably ok, but just wanted to know what caused the error.

**Comment by sequoiaKozak** [comment]
Unfortunately the error message isn't very helpful:

`[1] ./node_modules/react-native-super-grid/FlatGrid.js
[1] SyntaxError: /home/sequoia/Documents/Corcus/Repos/partner/frontend/node_modules/react-native-super-grid/FlatGrid.js: Unexpected token (89:10)
[1] 
[1]   87 | 
[1]   88 |         return (
[1] > 89 |           <View style={[rowStyle, additionalRowStyle, externalRowStyle]}>
[1]      |           ^
[1]   90 |             {rowItems.map((item, i) => (
[1]   91 |               <View
[1]   92 |                 key={
`

I'm using eslint, but adding /* eslint-disable */ to the top of the files doesn't fix it.

**Comment by saleel** [comment]
Can you try the below eslint rule

```
"rules": {
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }],
}
```

**Comment by saleel** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
